[project]
name = "winregkit"
version = "0.0.1"
description = "Helper library for Windows Registry operations"
requires-python = ">=3.11"
[license]
text = "MIT"

[project.scripts]
registry-cli = "registry_package.cli:main"

[project.optional-dependencies]
dev = ["pytest>=8.0", "mypy"]

[tool.mypy]
python_version = "3.11"
strict = true
files = ["src/winregkit"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
virtualenvs = true
dev-dependencies = ["pytest>=8.0"]

[tool.ruff]
line-length = 120
target-version = "py311"
src = ["src/winregkit"]
lint.extend-select = ["I"] # Ensure import order is checked

